fix: remove Multi-stage build & better test

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -55,7 +55,13 @@ jobs:
           docker run -d -p 3000:3000 --name test-container ${{ secrets.DOCKERHUB_USERNAME }}/nng4
           sleep 20
           docker logs test-container
-          curl http://127.0.0.1:3000/data/g/local/nng4/game.json
+          response=$(curl -s http://127.0.0.1:3000/data/g/local/nng4/game.json)
+          if [ -z "$response" ]; then
+              echo "Error: curl returned empty response" >&2
+              exit 1
+          else
+              echo "Response received: $response"
+          fi
           sleep 5
           docker logs test-container
           docker stop test-container
